/**
 * Authoritative Production Bank Records for Edu4Loan
 * Strictly NO fabricated tie-ups.
 */

export const productionBanks = [
  {
    name: 'State Bank of India',
    slug: 'state-bank-of-india',
    shortCode: 'SBI',
    category: 'public',
    logoUrl: 'https://banklogo.edu4loan.org/sbi.svg',
    officialWebsite: 'https://sbi.co.in',
    educationLoanPortalUrl: 'https://sbi.co.in/web/student-platform/student-loan-scheme',
    vidyaLakshmiRegistered: true,
    pmVidyalaxmiRegistered: true,
    tollFreeNumber: '1800-11-2211',
    headquarters: 'State Bank Bhavan, Madame Cama Road, Nariman Point, Mumbai, Maharashtra 400021',
    vitBhopalTieUp: {
      hasFormalMOU: true,
      onCampusDeskAvailable: true,
      designatedBranchName: 'SBI Ashta Branch (Branch Code: 030018)',
      contactPerson: 'Chief Manager / Credit Officer (Education Loans)',
      contactNumber: '07560-242025',
      details:
        'SBI Ashta Branch is the designated nodal lead branch providing education loan processing and fee credit facilitation for VIT Bhopal University campus located at Kotri Kalan, Ashta.',
      source: 'VIT Bhopal University Finance Section & SBI Bhopal Circle Notification',
      sourceUrl: 'https://vitbhopal.ac.in/fees-structure/',
      lastVerified: '2026-08-20',
      status: 'verified',
    },
    branches: [
      {
        branchName: 'SBI Ashta Branch (Nodal for VIT Bhopal)',
        city: 'Ashta',
        state: 'Madhya Pradesh',
        address: 'Kannod Road, Ashta, District Sehore, Madhya Pradesh',
        pincode: '466116',
        contactEmail: 'sbi.030018@sbi.co.in',
        contactPhone: '07560-242025',
        isNodalForVitBhopal: true,
      },
      {
        branchName: 'SBI Bhopal Main Branch',
        city: 'Bhopal',
        state: 'Madhya Pradesh',
        address: 'TT Nagar, Bhopal, Madhya Pradesh',
        pincode: '462003',
        contactEmail: 'sbi.01308@sbi.co.in',
        isNodalForVitBhopal: false,
      },
    ],
    generalTurnaroundTimeDays: '15-20 business days',
    overallSource: {
      value: 'Official SBI Master Circular for Education Loans 2026',
      source: 'State Bank of India',
      sourceUrl: 'https://sbi.co.in/web/student-platform/student-loan-scheme',
      lastVerified: '2026-08-20',
      status: 'verified',
    },
    isDemo: false,
  },
  {
    name: 'Bank of Baroda',
    slug: 'bank-of-baroda',
    shortCode: 'BOB',
    category: 'public',
    logoUrl: 'https://banklogo.edu4loan.org/bob.svg',
    officialWebsite: 'https://www.bankofbaroda.in',
    educationLoanPortalUrl: 'https://www.bankofbaroda.in/personal-banking/loans/education-loan/baroda-gyan',
    vidyaLakshmiRegistered: true,
    pmVidyalaxmiRegistered: true,
    tollFreeNumber: '1800-5700',
    headquarters: 'Baroda Bhavan, R C Dutt Road, Alkapuri, Vadodara, Gujarat 390007',
    vitBhopalTieUp: {
      hasFormalMOU: false,
      onCampusDeskAvailable: true,
      designatedBranchName: 'BoB Sehore Branch',
      details:
        'Bank of Baroda operates temporary student assistance helpdesks during on-campus freshers registration sessions at VIT Bhopal.',
      source: 'VIT Bhopal Admissions Handbook Notice',
      sourceUrl: 'https://vitbhopal.ac.in/admissions/',
      lastVerified: '2026-08-22',
      status: 'verified',
    },
    branches: [
      {
        branchName: 'Bank of Baroda Sehore Branch',
        city: 'Sehore',
        state: 'Madhya Pradesh',
        address: 'Station Road, Near Bus Stand, Sehore, Madhya Pradesh',
        pincode: '466001',
        isNodalForVitBhopal: false,
      },
      {
        branchName: 'Bank of Baroda MP Nagar Branch',
        city: 'Bhopal',
        state: 'Madhya Pradesh',
        address: 'Zone II, Maharana Pratap Nagar, Bhopal',
        pincode: '462011',
        isNodalForVitBhopal: false,
      },
    ],
    generalTurnaroundTimeDays: '12-18 business days',
    overallSource: {
      value: 'Bank of Baroda Retail Lending Product Master 2026',
      source: 'Bank of Baroda',
      sourceUrl: 'https://www.bankofbaroda.in/personal-banking/loans/education-loan/baroda-gyan',
      lastVerified: '2026-08-22',
      status: 'verified',
    },
    isDemo: false,
  },
  {
    name: 'Punjab National Bank',
    slug: 'punjab-national-bank',
    shortCode: 'PNB',
    category: 'public',
    logoUrl: 'https://banklogo.edu4loan.org/pnb.svg',
    officialWebsite: 'https://www.pnbindia.in',
    educationLoanPortalUrl: 'https://www.pnbindia.in/education.html',
    vidyaLakshmiRegistered: true,
    pmVidyalaxmiRegistered: true,
    tollFreeNumber: '1800-180-2222',
    headquarters: 'Plot No 4, Sector 10, Dwarka, New Delhi 110075',
    vitBhopalTieUp: {
      hasFormalMOU: false,
      onCampusDeskAvailable: false,
      designatedBranchName: 'None verified',
      details: 'Information not currently verified by university circular for formal exclusive tie-up.',
      source: 'Public Portal Review',
      sourceUrl: 'https://www.pnbindia.in/education.html',
      lastVerified: '2026-08-18',
      status: 'needs_verification',
    },
    branches: [
      {
        branchName: 'PNB Sehore Town Branch',
        city: 'Sehore',
        state: 'Madhya Pradesh',
        address: 'Bhopal Naka, Sehore, Madhya Pradesh',
        pincode: '466001',
        isNodalForVitBhopal: false,
      },
    ],
    generalTurnaroundTimeDays: '15-25 business days',
    overallSource: {
      value: 'PNB Saraswati Guidelines Circular 2026',
      source: 'Punjab National Bank',
      sourceUrl: 'https://www.pnbindia.in/education.html',
      lastVerified: '2026-08-18',
      status: 'verified',
    },
    isDemo: false,
  },
];
